source 'https://rubygems.org'

gem "rake"
gem "bundler"
gem 'nokogiri'
gem "cucumber"
gem "cucumber-rest-api", "= 0.3"
gem 'cucumber-api', '~> 0.3'

gem 'minke'
gem 'minke-generator-swift'
gem 'minke-generator-netmvc'
gem 'minke-generator-go'
